name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2.3.1
      - uses: pre-commit/action@v3.0.1
      - name: Set up Node.js 22.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 22.x
      - run: npm install
      - name: Run ESLint
        run: npm run lint
